'github actions':
  - all: ['.github/workflows/*']

source:
  - any: ['src/**/*']

documentation:
  - any:
      - 'wiki/**/*'
      - '**/*.md'

config:
  - any:
      - '*.json'
      - '*.yml'
      - '*.yaml'
      - '*.rc'
      
test:
  - any:
      - 'tests/**/*'
      - '**/*.spec.ts'
      - '**/*.test.ts'
