# Scope (Where?)
chore:
  - changed-files:
    - any-glob-to-any-file: ['package.json', 'bun.lockb', '.gitignore', 'README.md', 'LICENSE']

core:
  - changed-files:
    - any-glob-to-any-file: ['src/commands/**/*', 'src/functions/**/*', 'src/templates/**/*']

docs:
  - changed-files:
    - any-glob-to-any-file: ['wiki/**/*', '**/*.md']

domain:
  - changed-files:
    - any-glob-to-any-file: ['src/domain/**/*']

infra:
  - changed-files:
    - any-glob-to-any-file: ['src/infrastructure/**/*', 'docker/**/*', 'Dockerfile']

test:
  - changed-files:
    - any-glob-to-any-file: ['tests/**/*', '**/*.spec.ts']

ci:
  - changed-files:
    - any-glob-to-any-file: ['.github/**/*']
