# Scope (Where?)
chore:
  - any: ['package.json', 'bun.lockb', '.gitignore', 'README.md', 'LICENSE']

core:
  - any:
    - 'src/commands/**/*'
    - 'src/functions/**/*'
    - 'src/templates/**/*'

docs:
  - any:
    - 'wiki/**/*'
    - '**/*.md'

domain:
  - any: ['src/domain/**/*']

infra:
  - any:
    - 'src/infrastructure/**/*'
    - 'docker/**/*'
    - 'Dockerfile'

test:
  - any:
    - 'tests/**/*'
    - '**/*.spec.ts'

ci:
  - any: ['.github/**/*']
