# Scope (Where?)
chore:
  - 'package.json'
  - 'bun.lockb'
  - '.gitignore'
  - 'README.md'
  - 'LICENSE'

core:
  - 'src/commands/**/*'
  - 'src/functions/**/*'
  - 'src/templates/**/*'

docs:
  - 'wiki/**/*'
  - '**/*.md'

domain:
  - 'src/domain/**/*'

infra:
  - 'src/infrastructure/**/*'
  - 'docker/**/*'
  - 'Dockerfile'

test:
  - 'tests/**/*'
  - '**/*.spec.ts'

ci:
  - '.github/**/*'
