name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
      - uses: actions/checkout@master

      - name: 'Use Node'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: 'Change npm version'
          run: npm install -g npm@latest
      
      - run: npm ci
      - run: npm run build --if-present
